// <auto-generated />
namespace ProductStore.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.1.3-40302")]
    public sealed partial class CamponomeobrigatorioclasseCliente : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(CamponomeobrigatorioclasseCliente));
        
        string IMigrationMetadata.Id
        {
            get { return "201711221926118_Campo nome obrigatorio classe Cliente"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
